name: Deploy

on:
  push:
    branches:
      - main # or your deployment branch

permissions:
  id-token: write # Allows OIDC login flow with AWS
  contents: read

jobs:
  deploy:
    name: Deploy to S3 + CloudFront
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.0.1

      - name: Install Toolchain
        run: |
          cargo install --locked trunk
          rustup target add wasm32-unknown-unknown

      - name: Build
        run: |
          trunk build --release

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@56d6a583f00f6bad6d19d91d53a7bc3b8143d0e9 # v5.1.1
        with:
          role-to-assume: arn:aws:iam::122941220524:role/stones-github-actions-deploy-role
          aws-region: us-east-2

      - name: Sync S3 Bucket
        run: |
          aws s3 sync ./dist s3://jarpoole-stones --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id EURO0V9P5Q582 \
            --paths "/*"
